// <auto-generated />
using System;
using ISARMIN.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ISARMIN.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IsarminDbContext))]
    [Migration("20260719235800_Caja")]
    partial class Caja
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ISARMIN.Domain.Entities.Caja.Caja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Abierta")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_apertura");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<decimal>("MontoApertura")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monto_apertura");

                    b.Property<decimal?>("MontoFisicoDeclarado")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monto_fisico_declarado");

                    b.Property<decimal?>("MontoTeoricoCierre")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monto_teorico_cierre");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_cajas");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_cajas_usuario_id");

                    b.ToTable("cajas", null, t =>
                        {
                            t.HasCheckConstraint("ck_cajas_estado", "estado IN ('Abierta','Cerrada')");
                        });
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Caja.MovimientoCaja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CajaId")
                        .HasColumnType("uuid")
                        .HasColumnName("caja_id");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("concepto");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Monto")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monto");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_movimientos_caja");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_movimientos_caja_usuario_id");

                    b.HasIndex("CajaId", "Fecha")
                        .HasDatabaseName("ix_movimientos_caja_caja_id_fecha");

                    b.ToTable("movimientos_caja", null, t =>
                        {
                            t.HasCheckConstraint("ck_movimientos_caja_concepto", "concepto IN ('GastoOperativo','RetiroPropietario','AporteCapital')");

                            t.HasCheckConstraint("ck_movimientos_caja_monto", "monto > 0");

                            t.HasCheckConstraint("ck_movimientos_caja_tipo", "tipo IN ('Ingreso','Egreso')");
                        });
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Compras.Compra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DocumentoCompraNumero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("documento_compra_numero");

                    b.Property<string>("DocumentoCompraTipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("documento_compra_tipo");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_compras");

                    b.HasIndex("ProveedorId")
                        .HasDatabaseName("ix_compras_proveedor_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_compras_usuario_id");

                    b.ToTable("compras", (string)null);
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Compras.CompraDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("cantidad");

                    b.Property<Guid>("CompraId")
                        .HasColumnType("uuid")
                        .HasColumnName("compra_id");

                    b.Property<decimal>("CostoUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("costo_unitario");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.HasKey("Id")
                        .HasName("pk_compra_detalle");

                    b.HasIndex("CompraId")
                        .HasDatabaseName("ix_compra_detalle_compra_id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_compra_detalle_producto_id");

                    b.ToTable("compra_detalle", null, t =>
                        {
                            t.HasCheckConstraint("ck_compra_detalle_cantidad", "cantidad > 0");
                        });
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Configuracion.MedioPago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_medios_pago");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_medios_pago_nombre");

                    b.ToTable("medios_pago", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c1"),
                            Activo = true,
                            Nombre = "Efectivo"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c2"),
                            Activo = true,
                            Nombre = "Yape"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c3"),
                            Activo = true,
                            Nombre = "Plin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c4"),
                            Activo = true,
                            Nombre = "Transferencia bancaria"
                        });
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Identidad.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("accion");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modulo");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("Id")
                        .HasName("pk_permisos");

                    b.HasIndex("RolId", "Modulo", "Accion")
                        .IsUnique()
                        .HasDatabaseName("ix_permisos_rol_id_modulo_accion");

                    b.ToTable("permisos", null, t =>
                        {
                            t.HasCheckConstraint("ck_permisos_accion", "accion IN ('Crear','Editar','Eliminar','Consultar','Anular','Ajustar','Abrir','Cerrar','Registrar')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000b1"),
                            Accion = "Crear",
                            Modulo = "Usuarios",
                            RolId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000b2"),
                            Accion = "Editar",
                            Modulo = "Usuarios",
                            RolId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000b3"),
                            Accion = "Eliminar",
                            Modulo = "Usuarios",
                            RolId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000b4"),
                            Accion = "Consultar",
                            Modulo = "Usuarios",
                            RolId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000b5"),
                            Accion = "Consultar",
                            Modulo = "Roles",
                            RolId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000b6"),
                            Accion = "Crear",
                            Modulo = "Roles",
                            RolId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000b7"),
                            Accion = "Editar",
                            Modulo = "Roles",
                            RolId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Identidad.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_nombre");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Descripcion = "Acceso completo — Propietario.",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Descripcion = "Atención al cliente, ventas, caja, consulta de inventario.",
                            Nombre = "Ventas"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Descripcion = "Taller, diagnósticos, órdenes de trabajo, servicios de campo.",
                            Nombre = "Técnico"
                        });
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Identidad.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_hasta");

                    b.Property<string>("CredencialHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("credencial_hash");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("intentos_fallidos");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_usuario");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_nombre_usuario");

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuarios_estado", "estado IN ('Activo','Inactivo')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000a1"),
                            CredencialHash = "AQAAAAIAAYagAAAAEFF/mQcjo7I1pcwzMaEjr6h0JjtxjfNsg4QMpRJbGRHzyMbbydhPHhidcXlHS51ubQ==",
                            Estado = "Activo",
                            FechaCreacion = new DateTime(2026, 7, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            IntentosFallidos = 0,
                            Nombre = "Administrador ISARMIN",
                            NombreUsuario = "admin"
                        });
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Identidad.UsuarioRol", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("UsuarioId", "RolId")
                        .HasName("pk_usuario_rol");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_usuario_rol_rol_id");

                    b.ToTable("usuario_rol", (string)null);

                    b.HasData(
                        new
                        {
                            UsuarioId = new Guid("00000000-0000-0000-0000-0000000000a1"),
                            RolId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Inventario.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoriaPadreId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_padre_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.HasIndex("CategoriaPadreId")
                        .HasDatabaseName("ix_categorias_categoria_padre_id");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Inventario.MovimientoInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("MotivoAjuste")
                        .HasColumnType("text")
                        .HasColumnName("motivo_ajuste");

                    b.Property<Guid?>("OrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("origen_id");

                    b.Property<string>("OrigenTipo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origen_tipo");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_movimiento");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_movimientos_inventario");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_movimientos_inventario_usuario_id");

                    b.HasIndex("ProductoId", "Fecha")
                        .HasDatabaseName("ix_movimientos_inventario_producto_id_fecha");

                    b.ToTable("movimientos_inventario", null, t =>
                        {
                            t.HasCheckConstraint("ck_movimientos_inventario_origen_tipo", "origen_tipo IN ('Compra','Venta','OrdenTrabajo','ServicioCampo') OR origen_tipo IS NULL");

                            t.HasCheckConstraint("ck_movimientos_inventario_tipo_movimiento", "tipo_movimiento IN ('Compra','Venta','ConsumoTaller','ConsumoCampo','Ajuste','Devolucion')");
                        });
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Inventario.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_barras");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_interno");

                    b.Property<decimal>("CostoReferencia")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("costo_referencia");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("marca");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_venta");

                    b.Property<decimal>("StockActual")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("stock_actual");

                    b.Property<decimal?>("StockMinimo")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("stock_minimo");

                    b.Property<Guid>("UnidadMedidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidad_medida_id");

                    b.HasKey("Id")
                        .HasName("pk_productos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_productos_categoria_id");

                    b.HasIndex("CodigoBarras")
                        .IsUnique()
                        .HasDatabaseName("ix_productos_codigo_barras")
                        .HasFilter("codigo_barras IS NOT NULL");

                    b.HasIndex("CodigoInterno")
                        .IsUnique()
                        .HasDatabaseName("ix_productos_codigo_interno");

                    b.HasIndex("UnidadMedidaId")
                        .HasDatabaseName("ix_productos_unidad_medida_id");

                    b.ToTable("productos", null, t =>
                        {
                            t.HasCheckConstraint("ck_productos_estado", "estado IN ('Activo','Inactivo')");
                        });
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Inventario.UnidadMedida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_unidades_medida");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_unidades_medida_nombre");

                    b.ToTable("unidades_medida", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000d1"),
                            Nombre = "Unidad"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000d2"),
                            Nombre = "Metro"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000d3"),
                            Nombre = "Kilogramo"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000d4"),
                            Nombre = "Litro"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000d5"),
                            Nombre = "Rollo"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000d6"),
                            Nombre = "Par"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000d7"),
                            Nombre = "Juego"
                        });
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Terceros.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<string>("NombreRazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_razon_social");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_documento");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoCliente")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_cliente");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.ToTable("clientes", null, t =>
                        {
                            t.HasCheckConstraint("ck_clientes_estado", "estado IN ('Activo','Inactivo')");

                            t.HasCheckConstraint("ck_clientes_tipo_cliente", "tipo_cliente IS NULL OR tipo_cliente IN ('Natural','Juridica')");
                        });
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Terceros.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<string>("NombreRazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_razon_social");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_proveedores");

                    b.ToTable("proveedores", null, t =>
                        {
                            t.HasCheckConstraint("ck_proveedores_estado", "estado IN ('Activo','Inactivo')");
                        });
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Caja.Caja", b =>
                {
                    b.HasOne("ISARMIN.Domain.Entities.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cajas_usuarios_usuario_id");
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Caja.MovimientoCaja", b =>
                {
                    b.HasOne("ISARMIN.Domain.Entities.Caja.Caja", null)
                        .WithMany()
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_caja_cajas_caja_id");

                    b.HasOne("ISARMIN.Domain.Entities.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_caja_usuarios_usuario_id");
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Compras.Compra", b =>
                {
                    b.HasOne("ISARMIN.Domain.Entities.Terceros.Proveedor", null)
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_compras_proveedores_proveedor_id");

                    b.HasOne("ISARMIN.Domain.Entities.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_compras_usuarios_usuario_id");
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Compras.CompraDetalle", b =>
                {
                    b.HasOne("ISARMIN.Domain.Entities.Compras.Compra", null)
                        .WithMany("Detalles")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_compra_detalle_compras_compra_id");

                    b.HasOne("ISARMIN.Domain.Entities.Inventario.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_compra_detalle_productos_producto_id");
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Identidad.Permiso", b =>
                {
                    b.HasOne("ISARMIN.Domain.Entities.Identidad.Rol", null)
                        .WithMany("Permisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_permisos_roles_rol_id");
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Identidad.UsuarioRol", b =>
                {
                    b.HasOne("ISARMIN.Domain.Entities.Identidad.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol_roles_rol_id");

                    b.HasOne("ISARMIN.Domain.Entities.Identidad.Usuario", null)
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol_usuarios_usuario_id");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Inventario.Categoria", b =>
                {
                    b.HasOne("ISARMIN.Domain.Entities.Inventario.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaPadreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categorias_categorias_categoria_padre_id");
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Inventario.MovimientoInventario", b =>
                {
                    b.HasOne("ISARMIN.Domain.Entities.Inventario.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_inventario_productos_producto_id");

                    b.HasOne("ISARMIN.Domain.Entities.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_inventario_usuarios_usuario_id");
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Inventario.Producto", b =>
                {
                    b.HasOne("ISARMIN.Domain.Entities.Inventario.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_productos_categorias_categoria_id");

                    b.HasOne("ISARMIN.Domain.Entities.Inventario.UnidadMedida", null)
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_productos_unidades_medida_unidad_medida_id");
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Compras.Compra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Identidad.Rol", b =>
                {
                    b.Navigation("Permisos");
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Identidad.Usuario", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
