// <auto-generated />
using System;
using ISARMIN.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ISARMIN.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IsarminDbContext))]
    [Migration("20260719190037_CatalogosCategoriasYMediosPago")]
    partial class CatalogosCategoriasYMediosPago
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ISARMIN.Domain.Entities.Configuracion.MedioPago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_medios_pago");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_medios_pago_nombre");

                    b.ToTable("medios_pago", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c1"),
                            Activo = true,
                            Nombre = "Efectivo"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c2"),
                            Activo = true,
                            Nombre = "Yape"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c3"),
                            Activo = true,
                            Nombre = "Plin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c4"),
                            Activo = true,
                            Nombre = "Transferencia bancaria"
                        });
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Identidad.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("accion");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modulo");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("Id")
                        .HasName("pk_permisos");

                    b.HasIndex("RolId", "Modulo", "Accion")
                        .IsUnique()
                        .HasDatabaseName("ix_permisos_rol_id_modulo_accion");

                    b.ToTable("permisos", null, t =>
                        {
                            t.HasCheckConstraint("ck_permisos_accion", "accion IN ('Crear','Editar','Eliminar','Consultar','Anular')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000b1"),
                            Accion = "Crear",
                            Modulo = "Usuarios",
                            RolId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000b2"),
                            Accion = "Editar",
                            Modulo = "Usuarios",
                            RolId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000b3"),
                            Accion = "Eliminar",
                            Modulo = "Usuarios",
                            RolId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000b4"),
                            Accion = "Consultar",
                            Modulo = "Usuarios",
                            RolId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000b5"),
                            Accion = "Consultar",
                            Modulo = "Roles",
                            RolId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000b6"),
                            Accion = "Crear",
                            Modulo = "Roles",
                            RolId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000b7"),
                            Accion = "Editar",
                            Modulo = "Roles",
                            RolId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Identidad.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_nombre");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Descripcion = "Acceso completo — Propietario.",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Descripcion = "Atención al cliente, ventas, caja, consulta de inventario.",
                            Nombre = "Ventas"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Descripcion = "Taller, diagnósticos, órdenes de trabajo, servicios de campo.",
                            Nombre = "Técnico"
                        });
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Identidad.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_hasta");

                    b.Property<string>("CredencialHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("credencial_hash");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("intentos_fallidos");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_usuario");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_nombre_usuario");

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuarios_estado", "estado IN ('Activo','Inactivo')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000a1"),
                            CredencialHash = "AQAAAAIAAYagAAAAEFF/mQcjo7I1pcwzMaEjr6h0JjtxjfNsg4QMpRJbGRHzyMbbydhPHhidcXlHS51ubQ==",
                            Estado = "Activo",
                            FechaCreacion = new DateTime(2026, 7, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            IntentosFallidos = 0,
                            Nombre = "Administrador ISARMIN",
                            NombreUsuario = "admin"
                        });
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Identidad.UsuarioRol", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("UsuarioId", "RolId")
                        .HasName("pk_usuario_rol");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_usuario_rol_rol_id");

                    b.ToTable("usuario_rol", (string)null);

                    b.HasData(
                        new
                        {
                            UsuarioId = new Guid("00000000-0000-0000-0000-0000000000a1"),
                            RolId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Inventario.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoriaPadreId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_padre_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.HasIndex("CategoriaPadreId")
                        .HasDatabaseName("ix_categorias_categoria_padre_id");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Identidad.Permiso", b =>
                {
                    b.HasOne("ISARMIN.Domain.Entities.Identidad.Rol", null)
                        .WithMany("Permisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_permisos_roles_rol_id");
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Identidad.UsuarioRol", b =>
                {
                    b.HasOne("ISARMIN.Domain.Entities.Identidad.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol_roles_rol_id");

                    b.HasOne("ISARMIN.Domain.Entities.Identidad.Usuario", null)
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol_usuarios_usuario_id");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Inventario.Categoria", b =>
                {
                    b.HasOne("ISARMIN.Domain.Entities.Inventario.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaPadreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categorias_categorias_categoria_padre_id");
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Identidad.Rol", b =>
                {
                    b.Navigation("Permisos");
                });

            modelBuilder.Entity("ISARMIN.Domain.Entities.Identidad.Usuario", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
